module.exports = {
  common_01: 'Method not supported',
  common_02: 'Unspecified error',
  common_03: 'Data does not exist',
  common_04: 'Data already exists',
  common_api_01: 'Data already exists',
  common_api_02: '选定项目不存在',
  common_api_03: '文件类型错误',
  group_01: '用户组已存在',
  group_02: '用户组不存在',
  group_03: '叶子节点没有路径',
  group_04: '用户组下存在用户',
  group_05: '角色代码已存在',
  usersetting_01: '密码错误',
  usersetting_02: '用户不存在',
  operator_01: '组不存在',
  operator_02: '用户已经存在',
  operator_03: '用户不存在',
  operator_04: '用户下有未完成订单',
  menu_01: '菜单已经存在',
  menu_02: '菜单不存在',
  menu_03: '菜单下有子项',
  menu_04: '未配置路径',
  auth_05: '用户不存在或密码错误',
  auth_06: '电话不存在',
  auth_07: '类型不存在',
  auth_08: '发送验证码失败',
  auth_09: '验证码错误',
  auth_10: '用户组不存在',
  auth_11: '用户类型不存在',
  auth_12: '验证码错误',
  auth_13: '请输入正确的手机号码',
  auth_14: '请输入正确的用户类型',
  auth_15: 'type is missing',
  auth_16: 'phone is missing',
  auth_17: 'code is missing',
  auth_18: 'password is missing',
  auth_19: 'loginType is missing',
  auth_20: 'wxCode is missing',
  auth_21: '微信验证失败',
  auth_22: '用户不存在',
  auth_23: '验证码请求太频繁',
  auth_24: 'wrong password',
  billlading_01: 'billloading state error',
  billlading_02: 'billloading No in no stock',
  billlading_03: 'billloading not exist',
  customer_01: 'CUSTOMER Group Do not exist',
  booking_01: 'Only Customer',
  booking_02: 'Only Employee',
  blconfig_01: 'This Range been used',
  blconfig_02: 'Batch do not exist',
  import_01: 'Has been loaded',
  import_02: 'voyage is missing',
  import_03: 'VesselInformation sheet data incorrect',
  import_04: 'Please choose customer',
  import_05: 'Please choose carrier',
  import_06: 'Please choose invoice type',
  import_07: 'Please finish the invoice release',
  import_08: 'Please finish the verification',
  import_09: 'Invoice already release',
  import_10: 'Collect no freight charge',
  import_11: 'Freight charge is not number',
  import_12: 'BULKSHIPMENT do not exist',
  fee_01: 'Fee already exists, Please edit',
  fee_02: 'Fixed container deposit exists, Please invalid',
  fee_03: 'Fixed container deposit already approved, Please invalid',
  fee_04: 'Fixed container deposit do not exist',
  fee_05: 'Fixed container deposit already invalid',
  deposit_01: 'Must have container deposit',
  deposit_02: 'Must have invoice fee',
  deposit_03: 'IM, Freight collect must have Ocean Freight AND Invoice Fee',
  deposit_04: 'TR, Freight collect must have Ocean Freight',
  icd_01: 'Edit ICD do not exist',
  icd_02: 'ICD name or code already exists',
  do_01: 'D/O delivery or valid must be input',
  do_02: 'D/O delivery to customer do not exist',
  do_03: 'D/O delivery to must same to consignee name',
  do_04: 'D/O ICD do not exist',
  do_05: 'D/O ICD EMAIL do not exist',
  do_06: 'Return depot has locked',
  container_size_01: 'Edit contaienr size do not exist',
  container_size_02: 'Contaienr size name or code already exists',
  container_type_01: 'Edit contaienr type do not exist',
  container_type_02: 'Contaienr type name or code already exists',
  discharge_port_01: 'Edit discharge port do not exist',
  discharge_port_02: 'Discharge port name or code already exists',
  equipment_01: 'charge rule already exists',
  equipment_02: 'charge rule do not exist',
  equipment_03: 'container do not exist',
  equipment_04: 'receipt container do not exist',
  equipment_05: 'selected invoice containers contain other unreceipt container',
  edi_depot_01: 'Edit edi depot do not exist',
  edi_depot_02: 'edi depot name already exists',
}
